global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      # DEV
      - targets: ['host.docker.internal:3000'] 

  - job_name: 'financeiro-prod'
    scheme: https
    metrics_path: '/actuator/prometheus'
    static_configs:
      # PRODUÇÃO
      - targets: ['financeiropessoal-production.up.railway.app']  