#| Ambiente            | Comando                                                                                                                    |
#| ------------------- | ---------------------------------------------------------------------------------------------------------------------------|
#| **Dev (H2)**        | `docker-compose up --build` #Futuramente se necessário                                                                     |
#| **Dev (H2-memória)**| `mvn clean package -Dspring.profiles.active=dev` `java -jar target/backend-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev`|
#| **Prod (Postgres)** | `docker-compose -f docker-compose.yml -f docker-compose.prod.yml up --build`                                               |

# Comando para DEBUG #
# mvn spring-boot:run -Dspring-boot.run.profiles=dev -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

# Comando para RUN #
# mvn spring-boot:run -Dspring-boot.run.profiles=dev 

# Comando para BUILD #
# mvn clean package

# Comando para TEST #
# mvn test

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}  # Altere para 'prod' quando for subir o ambiente de produção ou use mvn clean package -Dspring.profiles.active=prod|dev

server:
  port: 3000

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION} 

