server:
    port: 3000

jwt:
    secret: s3cr3t-KL89nm@JkD7*!2vCxZopQYT349!nmLp0
    expiration: 86400000

spring:
    application:
        name: financeiro-api
# datasource: 
#  url:
#  username:
#  password:
#  driver-class-name:

    datasource:
        url: jdbc:h2:mem:financeirodb
        driver-class-name: org.h2.Driver
        username: sa
        password:

    sql:
        init:
            platform: h2

    h2:
        console:
            enabled: true
            path: /h2-console

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                'format_sql': true
       