name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build e testes
        working-directory: ./backend
        run: mvn clean verify
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: financeiro_test
          DB_USER: test_user
          DB_PASSWORD: test_password
          JWT_SECRET: testsecret
          JWT_EXPIRATION: 3600000

      - name: Executar análise SonarCloud
        working-directory: ./backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar -Dsonar.projectKey=uLemos_FinanceiroPessoal -Dsonar.organization=ulemos -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }}
      
      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem Docker
        working-directory: ./backend
        run: docker build -t ulemooss/financeiro-api:latest .

      - name: Push da imagem para Docker Hub
        run: docker push ulemooss/financeiro-api:latest

      - name: Instalar Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy para Railway
        working-directory: ./backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service FinanceiroPessoal --environment production

  